name: Deploy Next.js Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04  # ou ubuntu-24.04 selon votre préférence

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Installer curl si nécessaire
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Set up environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV


      # Installer Bun en utilisant l'action officielle
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'  # Vous pouvez spécifier une version spécifique si nécessaire


      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Start server and see
        run: bun run start 
